# Generated by Django 4.2.5 on 2023-10-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atachments',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework_url',
            field=models.URLField(max_length=300),
        ),
    ]
