# Generated by Django 4.2.5 on 2023-10-19 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_course_group_user_user_type_students_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
